config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get "/login" => "devise/sessions#new", as: :login
    delete "/logout" => "devise/sessions#destroy", as: :logout
    get "/signup" => "signup#new", as: :user_signup
    post "/signup" => "signup#create"
  end

  devise_for :users, controllers: { registrations: 'signup' }

  scope "/:year", constraints: { year: /\d{4}/ } do
    post "/register/login" => "registrations#login", as: :register_and_login
    get "/register/:step" => "registrations#new", as: :registration_step
    get "/register" => "registrations#new"
    post "/register" => "registrations#create"
    resource :registration, only: %i[show update]
    resources :scheduled_activities
    resource :itinerary do
      post :email
    end
    resource :account, only: [:show] do
      resources :payments, only: [:show, :new, :create]
    end
    scope "/:activity_type", constraints: { activity_type: /#{Activity.types.map(&:to_param).join('|')}/ } do
      get "/" => "activities#index", as: :activity_type
      get "/:id" => "activities#show", as: :activity
    end

    namespace :my, module: false do
      resources :workshops
    end

    get "/activities" => "activities#index", as: :activities

    scope "/code-of-conduct" do
      get "/" => "code_of_conduct#show", as: :code_of_conduct
      resources :incidents, only: [:new, :create]
    end

    get "/pricing" => "prices#index", as: :pricing
    get "/faq" => "faq#index", as: :faq
    get "/" => "festivals#show", as: :festival
  end

  resource :profile, only: %i[show update]

  resources :calendars, only: [:show]

  post "/payments/paypal/:id" => "payments#paypal", as: :paypal_callback
  post "/payments/:id" => "payments#show", as: :paypal_return
  get "/payments/:id" => "payments#show"

  namespace :admin do
    scope "/:year", constraints: { year: /\d{4}/ } do
      resource :festival, only: [:show, :edit, :update]
      resources :participants do
        resource :registration
      end
      resources :packages do
        put "reorder/:position" => "packages#reorder", on: :member
      end
      resources :activities
      resources :facilitators
      resource :timetable do
        resources :schedules, only: [:new, :create, :edit, :update, :destroy]
      end
      resources :venues do
        put "reorder/:position" => "venues#reorder", on: :member
      end

      get "payments/settings" => "payment_configurations#edit",
        as: :payment_settings
      match "payments/settings", to: "payment_configurations#update",
        via: [:put, :patch]

      resources :payments do
        collection do
          get "/:filter" => "payments#index", as: :filtered,
            constraints: { filter: /#{Payment.statuses.keys.join("|")}/ }
        end
        member do
          put :approve
          put :decline
        end
      end

      resources :vouchers

      scope "/reports" do
        get "/shows" => "reports#shows", as: :show_reports
        get "/show/:id" => "reports#show", as: :show_report
        get "/workshops" => "reports#workshops", as: :workshop_reports
        get "/workshop/:id" => "reports#show", as: :workshop_report
        get "/" => "reports#index", as: :reports
      end

      resources :bookings, except: [:index, :show]

      scope "/reports", constraints: { format: "csv" } do
        get "accounts" => "reports#accounts", as: :accounting_report
      end

      resources :incidents, only: [:index, :show] do
        resources :comments, except: [:index, :show]

        member do
          post :close
          post :reopen
        end
      end

      get "/" => "dashboards#show"
    end

    resources :participants, as: :users
    get "/" => "dashboards#show"
  end

  namespace :box_office do
    scope "/:year", constraints: { year: /\d{4}/ } do
      resources :shows, only: :show do
        resources :tickets, only: [:show, :edit, :update, :destroy]
      end

      root to: "shows#index"
    end
  end

  mount LetterOpenerWeb::Engine, at: "/admin/emails" if Rails.env.development?

  root to: "festivals#index"
end

app/views/postman/_itinerary.html.haml
%tr
  %td.content-block
    %hr
- itinerary.schedules.group_by(&:date).each do |date, schedules|
  %tr
    %td.content-block
      %h2.day= l(date, format: :full)
      = render partial: 'schedule', collection: schedules

app/views/postman/_schedule.html.haml
%p.activity-times= [schedule.starts_at, schedule.ends_at].map { |t| l(t, format: :ampm) }.join(' – ')
%h3.activity-name= schedule.activity.name
%p.activity-info= [schedule.activity.model_name.human, schedule.activity.facilitators.to_a.to_sentence].reject(&:blank?).join(" with ")
- if schedule.venue.present?
  %p.activity-venue= schedule.venue.name

app/views/postman/_thanks.html.haml
%tr
  %td.content-block
    Thanks,
    %br
    The NZIF team

app/views/postman/incident_report_notification.html.haml
%table.main{:cellpadding => '0', :cellspacing => '0', :width => '100%'}
  %tr
    %td.content-wrap
      %table{:cellpadding => '0', :cellspacing => '0', :width => '100%'}
        %tr
          %td.content-block
            = t('.text')
        %tr
          %td.content-block
            = link_to t('.link'), admin_incident_url(@festival, @incident)

app/views/postman/itinerary.html.haml
%table.main{:cellpadding => '0', :cellspacing => '0', :width => '100%'}
  %tr
    %td.alert
      = t('.updated', festival: @festival)
  %tr
    %td.content-wrap
      %table{:cellpadding => '0', :cellspacing => '0', :width => '100%'}
        %tr
          %td.content-block
            This is a confirmation of how your festival schedule looked at
            = succeed '.' do
              = l(Time.zone.now, format: :full)
        %tr
          %td.content-block
            The most up-to-date version of your itinerary is
            = succeed '.' do
              = link_to 'always online', itinerary_url(@festival)
            You can make changes there, or add festival events to your calendar.
        = render 'thanks'
        = render partial: 'itinerary', object: @itinerary

app/views/postman/receipt.html.haml
%table.main{:cellpadding => '0', :cellspacing => '0', :width => '100%'}
  %tr
    %td.alert
      = t('.payment_received', amount: @payment.total.format)
  %tr
    %td.content-wrap
      %table{:cellpadding => '0', :cellspacing => '0', :width => '100%'}
        %tr
          %td.content-block
            = t('.greeting', name: @participant.name)
        %tr
          %td.content-block
            = t('.copy', amount: @payment.total.format, festival: @festival.name)
        - if @account.paid_in_full?
          %tr
            %td.content-block
              = t('.paid_in_full')
        - else
          %tr
            %td.content-block
              = t('.remaining', outstanding: @account.total_to_pay.format)
          %tr
            %td.content-block
              = link_to t('.account_link', festival: @festival.name), account_url(@festival), class: 'btn-primary'
        = render 'thanks'

app/views/postman/registration_confirmation.html.haml
%table.main{:cellpadding => '0', :cellspacing => '0', :width => '100%'}
  %tr
    %td.alert
      = t('.registered', festival: @festival)
  %tr
    %td.content-wrap
      %table{:cellpadding => '0', :cellspacing => '0', :width => '100%'}
        %tr
          %td.content-block
            = t('.greeting', name: @participant.name)
        %tr
          %td.content-block
            = t('.intro')

        - @pending_payments.each do |payment|
          %tr
            %td.content-block
              = render partial: "/payments/instructions/#{payment.payment_method.key}", locals: { payment: payment }
        %tr
          %td.content-block
            = t('.next_steps')
        %tr
          %td.content-block
            = link_to t('.registration_link', festival: @festival.name), registration_url(@festival), class: 'btn-primary'
        %tr
          %td.content-block
            = t('.see_you')
        = render 'thanks'