config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get "/login" => "devise/sessions#new", as: :login
    delete "/logout" => "devise/sessions#destroy", as: :logout
    get "/signup" => "signup#new", as: :user_signup
    post "/signup" => "signup#create"
  end

  devise_for :users, controllers: { registrations: 'signup' }

  scope "/:year", constraints: { year: /\d{4}/ } do
    post "/register/login" => "registrations#login", as: :register_and_login
    get "/register/:step" => "registrations#new", as: :registration_step
    get "/register" => "registrations#new"
    post "/register" => "registrations#create"
    resource :registration, only: %i[show update]
    resources :scheduled_activities
    resource :itinerary do
      post :email
    end
    resource :account, only: [:show] do
      resources :payments, only: [:show, :new, :create]
    end
    scope "/:activity_type", constraints: { activity_type: /#{Activity.types.map(&:to_param).join('|')}/ } do
      get "/" => "activities#index", as: :activity_type
      get "/:id" => "activities#show", as: :activity
    end

    namespace :my, module: false do
      resources :workshops
    end

    get "/activities" => "activities#index", as: :activities

    scope "/code-of-conduct" do
      get "/" => "code_of_conduct#show", as: :code_of_conduct
      resources :incidents, only: [:new, :create]
    end

    get "/pricing" => "prices#index", as: :pricing
    get "/faq" => "faq#index", as: :faq
    get "/" => "festivals#show", as: :festival
  end

  resource :profile, only: %i[show update]

  resources :calendars, only: [:show]

  post "/payments/paypal/:id" => "payments#paypal", as: :paypal_callback
  post "/payments/:id" => "payments#show", as: :paypal_return
  get "/payments/:id" => "payments#show"

  namespace :admin do
    scope "/:year", constraints: { year: /\d{4}/ } do
      resource :festival, only: [:show, :edit, :update]
      resources :participants do
        resource :registration
      end
      resources :packages do
        put "reorder/:position" => "packages#reorder", on: :member
      end
      resources :activities
      resources :facilitators
      resource :timetable do
        resources :schedules, only: [:new, :create, :edit, :update, :destroy]
      end
      resources :venues do
        put "reorder/:position" => "venues#reorder", on: :member
      end

      get "payments/settings" => "payment_configurations#edit",
        as: :payment_settings
      match "payments/settings", to: "payment_configurations#update",
        via: [:put, :patch]

      resources :payments do
        collection do
          get "/:filter" => "payments#index", as: :filtered,
            constraints: { filter: /#{Payment.statuses.keys.join("|")}/ }
        end
        member do
          put :approve
          put :decline
        end
      end

      resources :vouchers

      scope "/reports" do
        get "/shows" => "reports#shows", as: :show_reports
        get "/show/:id" => "reports#show", as: :show_report
        get "/workshops" => "reports#workshops", as: :workshop_reports
        get "/workshop/:id" => "reports#show", as: :workshop_report
        get "/" => "reports#index", as: :reports
      end

      resources :bookings, except: [:index, :show]

      scope "/reports", constraints: { format: "csv" } do
        get "accounts" => "reports#accounts", as: :accounting_report
      end

      resources :incidents, only: [:index, :show] do
        resources :comments, except: [:index, :show]

        member do
          post :close
          post :reopen
        end
      end

      get "/" => "dashboards#show"
    end

    resources :participants, as: :users
    get "/" => "dashboards#show"
  end

  namespace :box_office do
    scope "/:year", constraints: { year: /\d{4}/ } do
      resources :shows, only: :show do
        resources :tickets, only: [:show, :edit, :update, :destroy]
      end

      root to: "shows#index"
    end
  end

  mount LetterOpenerWeb::Engine, at: "/admin/emails" if Rails.env.development?

  root to: "festivals#index"
end

app/views/shared/_flash.html.haml
- flash.each do |type, message|
  .flash{ class: type }
    %p
      %span= message

app/views/shared/_footer.html.haml
- unless hide_footer?
  %footer
    .inner
      %section.site-map
        %h3= homepage_link
        %ul
          - if festival.present?
            %li= link_to t('activities.index.title', year: festival.year), activities_path(festival)
            %li= link_to t('registrations.new.title'), register_path(festival.year)
            %li= link_to t('prices.index.title'), pricing_path(festival.year)
            %li= link_to t('code_of_conduct.show.title'), code_of_conduct_path(festival.year)
            %li= link_to t('faq.index.title'), faq_path(festival.year)

      %section.sponsors
        %h3 Our sponsors
        %ul
          %li
            %a{href: "http://www.nzimprovfestival.co.nz/trust", target: :_blank} New Zealand Improvisation Trust
          %li
            %a{href: "http://wellington.govt.nz/services/community-and-culture/funding/council-funds/creative-communities", target: :_blank} Creative Communities Scheme (WCC)
          %li
            %a{href: "http://www.bats.co.nz/", target: :_blank} BATS Theatre
          %li
            %a{href: "http://inkdigital.co.nz/", target: :_blank} Ink Digital

      %section
        %ul.social-media
          %li
            %a{href: "https://twitter.com/NZImprovFest", target: :_blank, rel: :twitter, title: "Twitter"}
          %li
            %a{href: "https://instagram.com/nzimprovfest", target: :_blank, rel: :instagram, title: "Instagram"}
          %li
            %a{href: "https://facebook.com/NZImprovFest", target: :_blank, rel: :facebook, title: "Facebook"}

app/views/shared/_head.html.haml
%meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
= title_tag
= csrf_meta_tags
%meta{name: "viewport", content: "width=device-width"}
%meta{name: "apple-mobile-web-app-capable", content: "yes"}
%meta{name: "mobile-web-app-capable", content: "yes"}
= stylesheet_link_tag 'https://fonts.googleapis.com/icon?family=Material+Icons'
= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Lato:300,400,700,900'
= render "/application/favicon"
= yield :head

app/views/shared/_navigation.html.haml
%nav
  .inner
    = homepage_link
    - if signed_in?
      .user-menu
        = link_to registration_path(festival), class: "user-menu-target" do
          = avatar(participant)
        %ul
          - if registration.present?
            = menu_link(t('header.links.registration', festival: festival.year), registration_path(festival), :assignment_ind, rel: 'registered')
            = menu_link(t('header.links.itinerary'), itinerary_path(festival), :local_activity)
            = menu_link(t('header.links.account'), account_path(festival), :account_balance)
          - else
            = menu_link(t('header.links.register', festival: festival.year), register_path(festival), :assignment_ind)
          - if participant.facilitator?
            = menu_link(t('header.links.my_workshops'), my_workshops_path(festival), :group_work)
          - if current_user.admin?
            = menu_link(t('header.links.festival_admin'), admin_festival_path(festival), :settings)
          = menu_link(t('header.links.profile'), profile_path, :face)
          = menu_link(t('header.authentication.log_out'), logout_path, :exit_to_app, method: :delete)
    - else
      = link_to t('header.authentication.log_in'), login_path

app/views/shared/_stub_time.html.haml
- if defined?(Timecop) && Timecop.top_stack_item
  = javascript_include_tag "sinon"
  - unix_millis = (Time.now.to_f * 1000.0).to_i
  :javascript
    sinon.useFakeTimers(#{unix_millis});