config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get "/login" => "devise/sessions#new", as: :login
    delete "/logout" => "devise/sessions#destroy", as: :logout
    get "/signup" => "signup#new", as: :user_signup
    post "/signup" => "signup#create"
  end

  devise_for :users, controllers: { registrations: 'signup' }

  scope "/:year", constraints: { year: /\d{4}/ } do
    post "/register/login" => "registrations#login", as: :register_and_login
    get "/register/:step" => "registrations#new", as: :registration_step
    get "/register" => "registrations#new"
    post "/register" => "registrations#create"
    resource :registration, only: %i[show update]
    resources :scheduled_activities
    resource :itinerary do
      post :email
    end
    resource :account, only: [:show] do
      resources :payments, only: [:show, :new, :create]
    end
    scope "/:activity_type", constraints: { activity_type: /#{Activity.types.map(&:to_param).join('|')}/ } do
      get "/" => "activities#index", as: :activity_type
      get "/:id" => "activities#show", as: :activity
    end

    namespace :my, module: false do
      resources :workshops
    end

    get "/activities" => "activities#index", as: :activities

    scope "/code-of-conduct" do
      get "/" => "code_of_conduct#show", as: :code_of_conduct
      resources :incidents, only: [:new, :create]
    end

    get "/pricing" => "prices#index", as: :pricing
    get "/faq" => "faq#index", as: :faq
    get "/" => "festivals#show", as: :festival
  end

  resource :profile, only: %i[show update]

  resources :calendars, only: [:show]

  post "/payments/paypal/:id" => "payments#paypal", as: :paypal_callback
  post "/payments/:id" => "payments#show", as: :paypal_return
  get "/payments/:id" => "payments#show"

  namespace :admin do
    scope "/:year", constraints: { year: /\d{4}/ } do
      resource :festival, only: [:show, :edit, :update]
      resources :participants do
        resource :registration
      end
      resources :packages do
        put "reorder/:position" => "packages#reorder", on: :member
      end
      resources :activities
      resources :facilitators
      resource :timetable do
        resources :schedules, only: [:new, :create, :edit, :update, :destroy]
      end
      resources :venues do
        put "reorder/:position" => "venues#reorder", on: :member
      end

      get "payments/settings" => "payment_configurations#edit",
        as: :payment_settings
      match "payments/settings", to: "payment_configurations#update",
        via: [:put, :patch]

      resources :payments do
        collection do
          get "/:filter" => "payments#index", as: :filtered,
            constraints: { filter: /#{Payment.statuses.keys.join("|")}/ }
        end
        member do
          put :approve
          put :decline
        end
      end

      resources :vouchers

      scope "/reports" do
        get "/shows" => "reports#shows", as: :show_reports
        get "/show/:id" => "reports#show", as: :show_report
        get "/workshops" => "reports#workshops", as: :workshop_reports
        get "/workshop/:id" => "reports#show", as: :workshop_report
        get "/" => "reports#index", as: :reports
      end

      resources :bookings, except: [:index, :show]

      scope "/reports", constraints: { format: "csv" } do
        get "accounts" => "reports#accounts", as: :accounting_report
      end

      resources :incidents, only: [:index, :show] do
        resources :comments, except: [:index, :show]

        member do
          post :close
          post :reopen
        end
      end

      get "/" => "dashboards#show"
    end

    resources :participants, as: :users
    get "/" => "dashboards#show"
  end

  namespace :box_office do
    scope "/:year", constraints: { year: /\d{4}/ } do
      resources :shows, only: :show do
        resources :tickets, only: [:show, :edit, :update, :destroy]
      end

      root to: "shows#index"
    end
  end

  mount LetterOpenerWeb::Engine, at: "/admin/emails" if Rails.env.development?

  root to: "festivals#index"
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :user, optional: true
  has_many :registrations, dependent: :destroy
  has_many :facilitators, dependent: :destroy
  has_many :vouchers, dependent: :destroy

  has_attached_file :avatar, styles: {
    small:  ['64x64#',   :jpg],
    medium: ['128x128#', :jpg],
    large:  ['256x256#', :jpg]
  }

  validates :name, presence: true
  validates :email,
    presence: true,
    unless: :user_email_present?
  validates :email,
    format: { with: Devise.email_regexp },
    uniqueness: { case_sensitive: false },
    if: :has_own_non_blank_email?
  validates_attachment_content_type :avatar, :content_type => %w(image/jpeg image/jpg image/png)

  scope :facilitators, -> { where('facilitators_count > 0') }

  def email
    [user.try(:email), super].reject(&:blank?).first
  end

  def user?
    user.present?
  end

  def facilitator?
    facilitators_count > 0
  end

  def to_s
    name
  end

  def <=>(another)
    name <=> another.name
  end

  def self.with_user
    includes(:user)
  end

  def self.by_name
    order(name: :asc)
  end

  private

  def has_own_non_blank_email?
    !read_attribute(:email).blank?
  end

  def user_email_present?
    user? && !user.email.blank?
  end
end

app/controllers/admin/participants_controller.rb
class Admin::ParticipantsController < Admin::Controller
  wrap_parameters :participant, include: ParticipantForm.parameters

  def index
    @participants = ParticipantList.new(
      festival: festival,
      show_all: params[:year].blank?
    )
  end

  def new
    @participant = ParticipantForm.new
  end

  def create
    @participant = ParticipantForm.new(nil, params)
    if @participant.save
      redirect_to admin_users_path
    else
      render :new
    end
  end

  def edit
    @participant = ParticipantForm.new(Participant.find(params[:id]))
  end

  def update
    @participant = ParticipantForm.new(Participant.find(params[:id]), params)
    if @participant.save
      redirect_to admin_users_path
    else
      render :edit
    end
  end
end

app/views/admin/participants/_form.html.haml
.field
  = form.label :name
  = form.text_field :name
  = form.error_messages_for :name
.field
  = form.label :email
  = form.email_field :email
  = form.error_messages_for :email
.field
  = form.label :admin do
    = form.check_box :admin, disabled: form.object.user == current_user
    Administrator?
.field
  = form.label :bio
  ~ form.text_area :bio, rows: 5
  = form.error_messages_for :bio
.field
  = form.label :origin
  = form.text_field :origin
  = form.error_messages_for :origin
.field
  = form.label :company
  = form.text_field :company
  = form.error_messages_for :company
.field
  = form.label :avatar
  = image_tag form.object.avatar.url(:medium) if form.object.avatar.present?
  = form.file_field :avatar
  = form.error_messages_for :avatar

app/views/admin/participants/_participant.html.haml
.participant{role: :listitem}
  = icon(:vpn_key, rel: :admin, title: t('.admin')) if participant.admin?
  = icon(:verified_user, rel: :verified, title: t('.verified')) if participant.verified_user?
  = link_to participant, edit_admin_user_path(participant), rel: :edit
  - if participant.registered?
    = link_to festival.name, admin_participant_registration_path(festival, participant), role: :button, rel: :registration
  - else
    = link_to t('.register'), new_admin_participant_registration_path(festival, participant), role: :button, rel: :register

app/views/admin/participants/edit.html.haml
- content_for :title, t('.title')
- content_for :navigation_button, back_button(admin_users_path)

%header
  %section
    %h1= t('.title')

%section
  = form_for @participant, url: admin_user_path(@participant) do |form|
    = render partial: "form", object: form
    %footer
      = form.submit t('.submit')

app/views/admin/participants/index.html.haml
- content_for :title, t('.title')

%header
  %section
    %h1= t('.title')
    %p
      = link_to_if @participants.show_all?, festival.name, admin_participants_path(festival) do
        %span= festival.name
      = link_to_unless @participants.show_all?, t('.show.all'), admin_users_path do
        %span= t('.show.all')
  %aside
    = link_to new_admin_user_path, role: :button do
      = icon :add

%section
  .participants{role: :list}
    %header
      %input{type: :search, placeholder: t('.search')}
      %label= icon :search
    = render("empty")
    = render(@participants)

app/views/admin/participants/new.html.haml
- content_for :title, t('.title')

%header
  %section
    %h1= t('.title')

%section
  = form_for @participant, url: admin_users_path do |form|
    = render partial: "form", object: form
    %footer
      = form.submit t('.submit')

app/views/admin/participants/show.html.haml
%h1 Admin::Participants#show
%p Find me in app/views/admin/participants/show.html.haml