config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get "/login" => "devise/sessions#new", as: :login
    delete "/logout" => "devise/sessions#destroy", as: :logout
    get "/signup" => "signup#new", as: :user_signup
    post "/signup" => "signup#create"
  end

  devise_for :users, controllers: { registrations: 'signup' }

  scope "/:year", constraints: { year: /\d{4}/ } do
    post "/register/login" => "registrations#login", as: :register_and_login
    get "/register/:step" => "registrations#new", as: :registration_step
    get "/register" => "registrations#new"
    post "/register" => "registrations#create"
    resource :registration, only: %i[show update]
    resources :scheduled_activities
    resource :itinerary do
      post :email
    end
    resource :account, only: [:show] do
      resources :payments, only: [:show, :new, :create]
    end
    scope "/:activity_type", constraints: { activity_type: /#{Activity.types.map(&:to_param).join('|')}/ } do
      get "/" => "activities#index", as: :activity_type
      get "/:id" => "activities#show", as: :activity
    end

    namespace :my, module: false do
      resources :workshops
    end

    get "/activities" => "activities#index", as: :activities

    scope "/code-of-conduct" do
      get "/" => "code_of_conduct#show", as: :code_of_conduct
      resources :incidents, only: [:new, :create]
    end

    get "/pricing" => "prices#index", as: :pricing
    get "/faq" => "faq#index", as: :faq
    get "/" => "festivals#show", as: :festival
  end

  resource :profile, only: %i[show update]

  resources :calendars, only: [:show]

  post "/payments/paypal/:id" => "payments#paypal", as: :paypal_callback
  post "/payments/:id" => "payments#show", as: :paypal_return
  get "/payments/:id" => "payments#show"

  namespace :admin do
    scope "/:year", constraints: { year: /\d{4}/ } do
      resource :festival, only: [:show, :edit, :update]
      resources :participants do
        resource :registration
      end
      resources :packages do
        put "reorder/:position" => "packages#reorder", on: :member
      end
      resources :activities
      resources :facilitators
      resource :timetable do
        resources :schedules, only: [:new, :create, :edit, :update, :destroy]
      end
      resources :venues do
        put "reorder/:position" => "venues#reorder", on: :member
      end

      get "payments/settings" => "payment_configurations#edit",
        as: :payment_settings
      match "payments/settings", to: "payment_configurations#update",
        via: [:put, :patch]

      resources :payments do
        collection do
          get "/:filter" => "payments#index", as: :filtered,
            constraints: { filter: /#{Payment.statuses.keys.join("|")}/ }
        end
        member do
          put :approve
          put :decline
        end
      end

      resources :vouchers

      scope "/reports" do
        get "/shows" => "reports#shows", as: :show_reports
        get "/show/:id" => "reports#show", as: :show_report
        get "/workshops" => "reports#workshops", as: :workshop_reports
        get "/workshop/:id" => "reports#show", as: :workshop_report
        get "/" => "reports#index", as: :reports
      end

      resources :bookings, except: [:index, :show]

      scope "/reports", constraints: { format: "csv" } do
        get "accounts" => "reports#accounts", as: :accounting_report
      end

      resources :incidents, only: [:index, :show] do
        resources :comments, except: [:index, :show]

        member do
          post :close
          post :reopen
        end
      end

      get "/" => "dashboards#show"
    end

    resources :participants, as: :users
    get "/" => "dashboards#show"
  end

  namespace :box_office do
    scope "/:year", constraints: { year: /\d{4}/ } do
      resources :shows, only: :show do
        resources :tickets, only: [:show, :edit, :update, :destroy]
      end

      root to: "shows#index"
    end
  end

  mount LetterOpenerWeb::Engine, at: "/admin/emails" if Rails.env.development?

  root to: "festivals#index"
end

app/controllers/admin/reports_controller.rb
class Admin::ReportsController < Admin::Controller
  def index
  end

  def shows
    @activities = ShowList.new(festival)
    render 'activities'
  end

  def show
    @activity = ShowBookings.new(schedule)
    render 'activity'
  end

  def workshops
    @activities = WorkshopList.new(festival)
    render 'activities'
  end

  def accounts
    @report = AccountingReport.new(festival)

    respond_to do |format|
      format.csv do
        send_data @report.to_csv, filename: @report.filename
      end
    end
  end

  private

  def schedule
    @schedule ||= festival.schedules
      .includes(:activity, :venue, :selections => { :registration => :participant })
      .find(params[:id])
  end
end

app/views/admin/reports/_activity.html.haml
%li
  = link_to admin_show_report_path(festival, activity) do
    = fullness_graph(activity.count, activity.limit, text: false)
    .details
      %b= activity.name
      %small= [activity.times, activity.venue].compact.join(" in ")

app/views/admin/reports/_booking.html.haml
%li
  = link_to edit_admin_booking_path(festival, booking.selection) do
    = icon :face
    %span= booking.name

app/views/admin/reports/activities.html.haml
- content_for :title, @activities.title

%header
  .inner
    %h1= @activities.title

- @activities.to_a.group_by(&:date).each do |date, activities|
  %section.box-office-list
    .inner
      %h3= date
      %ul.shows
        = render partial: 'admin/reports/activity', collection: activities

app/views/admin/reports/activity.html.haml
- content_for :title, @activity.name

%header
  %section
    %h1= @activity.name
    %p
      %span= @activity.date_and_time
  %aside
    = link_to @activity.back_path, rel: :back do
      Back

%section.box-office-tickets
  .inner
    %h2
      = [@activity.count, @activity.limit].compact.join(' of ')
      = 'ticket'.pluralize(@activity.limit || @activity.count)
      sold
    %ul.tickets
      = render partial: 'admin/reports/booking', collection: @activity.bookings

app/views/admin/reports/index.html.haml
- content_for :title, t('.title')

%header
  .inner
    %h1= t('.title')

%section
  .inner
    %ul
      %li= link_to 'Workshops', admin_workshop_reports_path(festival)
      %li= link_to 'Shows', admin_show_reports_path(festival)